In [1]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [2]:
[1,2,3]*[4,5,6]

TypeError: can't multiply sequence by non-int of type 'list'

# Numerical Pyhthon

In [5]:
import numpy as np

In [4]:
[1,2,3]*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [6]:
a=np.array([1,2,3])

In [7]:
a

array([1, 2, 3])

In [8]:
a*3

array([3, 6, 9])

# Math Function

In [9]:
np.sum(a)

6

In [10]:
np.mean(a)

2.0

In [11]:
np.absolute(a)

array([1, 2, 3])

In [12]:
np.add(a)

ValueError: invalid number of arguments

In [13]:
np.std(a)

0.816496580927726

In [14]:
np.mean(a)

2.0

# arange, linspace, logspace
##### arange (array range) hampir sama seperti range, tapi dalam bentuk array,Return evenly spaced values within a given interval.
array([0, 1, 2, 3, 4])
   ##### linspace (Return evenly spaced numbers over a specified interval.) atau memecah range berdasarkan jumlah pembagian nya*
   ##### logspace (pangkat dari 10) Return numbers spaced evenly on a log scale.



In [16]:
np.arange(0,5,)

array([0, 1, 2, 3, 4])

In [17]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [20]:
np.logspace(-2,4,4)

array([1.e-02, 1.e+00, 1.e+02, 1.e+04])

# Random

In [79]:
np.random.rand(2,3)

array([[0.98379008, 0.58258833, 0.84805321],
       [0.02695718, 0.55230974, 0.70567604]])

# Control Randomness
pengecakan yang terkontrol, untuk scientist publikasi ilmiah, untuk pembuktian ilmiah yang memerlukan shuffle atau pengacakan data.
* np.random.RandomState()

In [57]:
state= np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])